name: gift_keys
description: A new Flutter project.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0


  # Local storage
  sqlite_async: ^0.11.4
  sqlite3_flutter_libs: ^0.5.31

  # Navigator
  go_router: ^14.2.9

  # State Management
  bloc_concurrency: ^0.3.0
  flutter_bloc: ^9.0.0
  hydrated_bloc: ^10.0.0

  # UI
  dynamic_color: ^1.7.0
  rive: ^0.13.20

  # Utils
  clock: ^1.1.2
  collection: ^1.19.1
  equatable: ^2.0.5
  file: ^7.0.1
  flutter_image_compress: ^2.4.0
  image_picker: ^1.1.2
  get_it: ^8.0.0
  logger: ^2.4.0
  nfc_manager:
    git:
      url: https://github.com/ngoc-quoc-huynh/nfc_manager.git
      path: nfc_manager
      ref: v1.0.1
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  url_launcher: ^6.3.1

dev_dependencies:
  # Linter
  cosee_lints: ^0.9.0
  dart_code_linter: ^2.0.0

  # Localization
  slang_flutter: ^4.0.0
  slang_build_runner: ^4.0.0

  # Launcher icon
  flutter_launcher_icons: ^0.14.3

  # Splash Screen
  flutter_native_splash: ^2.4.1

  # Test
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  meta: ^1.16.0
  mocktail: ^1.0.4
  test_cov_console: ^0.2.2

flutter:
  uses-material-design: true

  assets:
    - assets/key.riv
    - assets/launcher_icon.webp
