name: gift_keys
description: A new Flutter project.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter

  # Navigator
  go_router: ^14.2.9

  # State Management
  flutter_bloc: ^9.0.0
  bloc_concurrency: ^0.3.0

  # Utils
  equatable: ^2.0.5
  get_it: ^8.0.0
  logger: ^2.4.0

dev_dependencies:
  # Linter
  cosee_lints: ^0.8.0
  dart_code_linter: ^2.0.0

  # Localization
  slang_flutter: ^4.0.0
  slang_build_runner: ^4.0.0

  # Launcher icon
  flutter_launcher_icons: ^0.14.1

  # Splash Screen
  flutter_native_splash: ^2.4.1

  # Test
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.4
  test_cov_console: ^0.2.2

flutter:
  uses-material-design: true
