name: gift_box

on:
  push:
    paths:
      - 'gift_box/**'
      - '.github/workflows/gift_box.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    environment: gift_box

    defaults:
      run:
        working-directory: ./gift_box

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: 'gradle'

      - name: Setup asdf
        uses: asdf-vm/actions/setup@v3
      - name: Cache asdf
        uses: actions/cache@v4
        with:
          path: |
            ~/.asdf/installs
            ~/.asdf/plugins
            ~/.asdf/shims
          key: ${{ runner.os }}-asdf-${{ hashFiles('.tool-versions') }}
          restore-keys: ${{ runner.os }}-asdf-
      - name: Install asdf
        uses: asdf-vm/actions/install@v3
        # See https://github.com/asdf-vm/actions/issues/445
        if: steps.cache-asdf.outputs.cache-hit != 'true'
      - name: Reshim asdf
        run: asdf reshim

      - name: Cache flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ./gift_box/.dart_tool
          key: ${{ runner.os }}-flutter-gift-box-${{ hashFiles('./gift_box/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-flutter-gift-box-
      - name: Install dependencies
        run: flutter pub get

      - name: Generate i18n
        run: dart run slang generate
      - name: Format code
        run: dart format --set-exit-if-changed .
      - name: Analyze code
        run: flutter analyze
      - name: Run code metrics
        run: dart run dart_code_linter:metrics analyze . --set-exit-on-violation-level=warning
      - name: Run tests
        run: |
          flutter test --coverage --test-randomize-ordering-seed=random --dart-define=CI=true
          dart run test_cov_console --exclude=static,domain/interfaces,injector.dart
      - name: Upload golden test failures
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: golden-test-failures
          path: gift_box/test/ui/**/failures

      - name: Generate key.properties file
        if: github.event_name == 'workflow_dispatch'
        env:
          KEY_PROPERTIES_FILE: ./android/key.properties
        run: |
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" > ${{ env.KEY_PROPERTIES_FILE }}
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> ${{ env.KEY_PROPERTIES_FILE }}
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> ${{ env.KEY_PROPERTIES_FILE }}
      - name: Generate keystore file
        if: github.event_name == 'workflow_dispatch'
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/gift_bpx.jks
      - name: Build APK
        if: github.event_name == 'workflow_dispatch'
        run: |
          flutter build apk \
            --release \
            --obfuscate \
            --split-debug-info=./build/app/outputs/symbols
      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          name: Gift Keys APK
          path: |
            app/build/app/outputs/apk/release/gift_box_release_v*.apk
            build/app/outputs/symbols
